// Generated by tools/generate_combat_4c_fixtures.py. Offline only.
std::vector<Profile> AuthoredProfiles() { return {
    {{"FalloutNV.esm",0x00020420u},1u,0x00000004u,{{Extent::None, Extent::Partial, Extent::Partial, Extent::Partial, Extent::Partial, Extent::Partial}}},
    {{"FalloutNV.esm",0x00020426u},1u,0x00000602u,{{Extent::Partial, Extent::None, Extent::None, Extent::None, Extent::None, Extent::None}}},
}; }
struct CapturedFixture { Input input; unsigned headPartial, torsoPartial; };
std::vector<CapturedFixture> CapturedFixtures() {
    std::vector<CapturedFixture> rows;
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A796124DDFA0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      input.items[1]={0x0015A79612550E60ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=1;
      input.items[0]={0x0015A796124DDFA0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,0.5};
      rows.push_back({input,0,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=0;
      rows.push_back({input,0,0}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A796124DDFA0ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A7961247ABE0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612005500ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A79612005520ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    { Input input; input.target=Target::EquipmentCharacter;
      input.enumerationComplete=true; input.stableDoubleRead=true;
      input.count=2;
      input.items[0]={0x0015A79612479A00ull,{"FalloutNV.esm",0x00020426u},true,0x00000602u,1};
      input.items[1]={0x0015A796120050C0ull,{"FalloutNV.esm",0x00020420u},true,0x00000004u,1};
      rows.push_back({input,1,1}); }
    return rows;
}
