// Generated by tools/prepare_combat_3s.py; retain BallistX/Ravuth credit.
// Source archive SHA256: d71fe28f1262dec7a0f2086f06b243168d74a3f11d8b57cd8b7b8127c9506e3d
constexpr Profile kProfiles[] = {
    {"9mm-pistol-standard", {"FalloutNV.esm:0E3778", "FalloutNV.esm:08ED03", "FalloutNV.esm:08F20F"}, 115, 0.35499999999999998},
    {"hunting-rifle-standard-308", {"FalloutNV.esm:004333", "FalloutNV.esm:06B53C", "FalloutNV.esm:08F20A"}, 147, 0.308},
};
