"""Validate authored JSON and emit offline C++ fixtures from pinned 4B captures."""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / 'native/NVOCombatModel'
STEP = ROOT / 'source/combat/step4c'
PROFILE = STEP / 'profiles/armour-coverage.json'
REGIONS = ['head','torso','left_arm','right_arm','left_leg','right_leg']
EXTENTS = dict(none='None', partial='Partial', full='Full', unknown='Unknown')
CAPTURES = {
    'source/combat/step4b/Evidence/LIVE-4B-20260916-233442.log': '1d20983e4d196d41f485853e2eac64ac0eaa49daede615ba971eb696ec138501',
    'source/combat/step4b/stress/LIVE-4B-STRESS-20260916-235307.log': '555081337821fb407cb29afa59ca98b86f174766b2a108d1e1675b8849ad7ace',
}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def unique_object(pairs):
    value = {}
    for key, item in pairs:
        if key in value: raise ValueError('duplicate JSON field: '+key)
        value[key] = item
    return value
def load_document(text):
    return json.loads(text, object_pairs_hook=unique_object)
def validate(document):
    if set(document) != {'schema_version','policy','regions','profiles'} or type(document['schema_version']) is not int or document['schema_version'] != 1:
        raise ValueError('schema')
    if document['regions'] != REGIONS or not isinstance(document['policy'], str) or not document['policy']:
        raise ValueError('regions/policy')
    profiles = document['profiles']
    if not isinstance(profiles, list) or not 1 <= len(profiles) <= 256: raise ValueError('profile count')
    keys, ids = set(), set()
    for p in profiles:
        if not isinstance(p, dict) or set(p) != {'id','plugin','local_id','revision','expected_equip_mask','coverage','rationale'}:
            raise ValueError('profile fields')
        if not isinstance(p['plugin'], str) or not re.fullmatch(r'[ -~]{5,128}', p['plugin']) or any(c in p['plugin'] for c in '/\\:*?"<>|') or '..' in p['plugin'] or p['plugin'] != p['plugin'].strip() or not p['plugin'].lower().endswith(('.esm','.esp')):
            raise ValueError('plugin key')
        for field in ('local_id','expected_equip_mask'):
            if not isinstance(p[field], str) or not re.fullmatch(r'[0-9A-Fa-f]{8}', p[field]): raise ValueError(field)
        local, mask = int(p['local_id'],16), int(p['expected_equip_mask'],16)
        if not 0 < local <= 0xFFFFFF or not 0 < mask <= 0xFFFFF: raise ValueError('id/mask range')
        if type(p['revision']) is not int or not 0 < p['revision'] <= 0xFFFFFFFF: raise ValueError('revision')
        if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9-]{1,64}',p['id']) or not isinstance(p['rationale'], str) or not p['rationale']: raise ValueError('id/rationale')
        if not isinstance(p['coverage'], dict) or set(p['coverage']) != set(REGIONS) or any(type(v) is not str or v not in EXTENTS for v in p['coverage'].values()): raise ValueError('explicit coverage required')
        key = (p['plugin'].lower(), local)
        if key in keys or p['id'] in ids: raise ValueError('ambiguous duplicate profile')
        keys.add(key); ids.add(p['id'])
    return profiles

def main():
    document = load_document(PROFILE.read_text())
    profiles = validate(document)
    generated = ['// Generated by tools/generate_combat_4c_fixtures.py. Offline only.',
                 'std::vector<Profile> AuthoredProfiles() { return {']
    for p in profiles:
        extents = ', '.join('Extent::'+EXTENTS[p['coverage'][r]] for r in REGIONS)
        generated.append('    {{"%s",0x%su},%du,0x%su,{{%s}}},' % (p['plugin'],p['local_id'],p['revision'],p['expected_equip_mask'],extents))
    generated += ['}; }', 'struct CapturedFixture { Input input; unsigned headPartial, torsoPartial; };',
                  'std::vector<CapturedFixture> CapturedFixtures() {', '    std::vector<CapturedFixture> rows;']
    fixture_records = []
    for path, expected in CAPTURES.items():
        capture = ROOT / path
        if sha(capture) != expected: raise ValueError('capture changed')
        lines = capture.read_text().splitlines()
        parsed = [(line.split()[0], dict(re.findall(r'\b([A-Za-z_][A-Za-z_0-9]*)=([^\s]+)', line))) for line in lines if line]
        for kind, snap in parsed:
            if kind != 'ARMOUR_SNAPSHOT': continue
            if snap['stable_double_read'] != '1' or snap['enumeration_complete'] != '1': raise ValueError('incomplete replay fixture')
            items = [r for k,r in parsed if k == 'ARMOUR_ITEM' and (r['session'],r['seq']) == (snap['session'],snap['seq'])]
            if len(items) != int(snap['equipped_armour_count']): raise ValueError('partial capture')
            # Explicit origin evidence for these two base-game forms only. Never strip a load index.
            if any(r['form'] not in {'00020420','00020426'} for r in items): raise ValueError('unresolved form origin')
            generated += ['    { Input input; input.target=Target::EquipmentCharacter;',
                          '      input.enumerationComplete=true; input.stableDoubleRead=true;',f'      input.count={len(items)};']
            for i, r in enumerate(items):
                generated.append('      input.items[%d]={0x%sull,{"FalloutNV.esm",0x%su},true,0x%su,%s};' % (i,r['instance'],r['form'],r['part_mask'],r['condition_ratio']))
            head = sum(r['form'] == '00020426' for r in items)
            torso = sum(r['form'] == '00020420' for r in items)
            generated.append(f'      rows.push_back({{input,{head},{torso}}}); }}')
            fixture_records.append(dict(capture=path,session=snap['session'],seq=snap['seq'],target=snap['target'],item_count=len(items),head_partial=head,torso_partial=torso))
    generated += ['    return rows;', '}']
    (MODEL / 'CoverageFixtures.inl').write_text('\n'.join(generated)+'\n', encoding='ascii')
    (STEP / 'REPLAY-INPUTS.json').write_text(json.dumps(dict(profile_sha256=sha(PROFILE),captures=CAPTURES,
        form_origin_policy='Only exact observed runtime forms00020420/00020426 mapped to FalloutNV.esm. No general load-index resolution.',
        fixtures=fixture_records),indent=2)+'\n',encoding='utf-8')
    print(json.dumps(dict(profiles=len(profiles),captured_snapshots=len(fixture_records),generated_sha256=sha(MODEL/'CoverageFixtures.inl'))))
if __name__ == '__main__': main()
