"""Build/test an OFFLINE energy-input packet; no writes outside the workspace."""
from pathlib import Path
from collections import Counter
import hashlib
import json
import math
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / 'native/NVOCombatModel'
OUT = ROOT / 'source/combat/step3s'
BUILD = OUT / 'out'
ARCHIVE = Path(r'C:/Users/regan/Desktop/NVO Mod References (Open Source)/BallistX-70341-5-4-1712065466.rar')
GAME = Path(r'C:/Users/regan/Desktop/Steam Install Folder/steamapps/common/Fallout New Vegas')
CAPTURES = [
    ('3G2', 'source/combat/step3g2/captures/2026-09-15-3G2-5c4e764753b7/NVOCombatCore.log', '5c4e764753b73c258a176e4270b5b5bdbf8255ac6d35c097daa259cf89fcca63'),
    ('3Q', 'source/combat/step3q/captures/review-37821ee73c00/NVOCombatCore.log', '37821ee73c001055b279fc56af83b8c57471ccefc16caac7e8e9a83fbde30b64'),
]

def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()

def write_json(p, value):
    p.write_text(json.dumps(value, indent=2, allow_nan=False) + '\n', encoding='utf-8')

def require(condition, message):
    if not condition:
        raise ValueError(message)

def rows(path):
    result = []
    for number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        if line.startswith(('FLIGHT_PROFILE ', 'IMPACT_')):
            result.append((line.split()[0], dict(re.findall(r'(\w+)=([^\s]+)', line)), number))
    return result

def one(index, kind, key):
    found = index.get((kind, key), [])
    require(len(found) == 1, f'{kind} {key}: missing/ambiguous companion ({len(found)})')
    return found[0]

def main():
    BUILD.mkdir(parents=True, exist_ok=True)
    donor_meta_path = ROOT / 'source/combat/step3a/PROVENANCE.json'
    pilot_path = ROOT / 'source/combat/step3a/NVO-Flight-Pilot.json'
    donor = json.loads(donor_meta_path.read_text())
    require(sha(ARCHIVE) == donor['sha256'], 'BallistX archive changed')
    extracted = {}
    for name in ('Config/BallistX/Data/CartridgeData.cfg', 'Config/BallistX/Help.txt'):
        raw = subprocess.run(['tar', '-xOf', str(ARCHIVE), name], capture_output=True, check=True).stdout
        require(hashlib.sha256(raw).hexdigest() == donor['members'][name]['sha256'], f'donor member changed: {name}')
        extracted[name] = raw.decode('cp1252').replace('\r\r\n', '\n').replace('\r\n', '\n')
    require('4: Mass in gr' in extracted['Config/BallistX/Help.txt'], 'donor mass unit changed')
    pilot = json.loads(pilot_path.read_text())
    profiles = pilot['profiles']
    require(len(profiles) == 2, 'scope changed')
    generated = ['// Generated by tools/prepare_combat_3s.py; retain BallistX/Ravuth credit.',
                 '// Source archive SHA256: ' + donor['sha256'], 'constexpr Profile kProfiles[] = {']
    manifest_profiles = []
    for p in profiles:
        k = p['match']; source = p['donor_source']['cartridge']
        exact = [line for line in extracted[source['member']].splitlines() if line.split(';')[0].split()
                 and line.split(';')[0].split()[0] == '@' + k['projectile_base']]
        require(exact == [source['original_row']], 'selected donor row changed or duplicate')
        columns = exact[0].split(';')[0].split()
        grain, inch = float(columns[3]), float(columns[4])
        require(grain == p['flight_inputs']['mass_grain'] and inch == p['flight_inputs']['diameter_in'], 'pilot mass mismatch')
        generated.append('    {"%s", {"%s", "%s", "%s"}, %.17g, %.17g},' %
                         (p['id'], k['weapon'], k['ammunition'], k['projectile_base'], grain, inch))
        manifest_profiles.append(dict(id=p['id'], match=k, mass_grains=grain, mass_kg=grain*0.00006479891,
                                      diameter_inches=inch, diameter_m=inch*.0254, donor_row=source))
    generated.append('};')
    (MODEL/'ImpactEnergyProfiles.inl').write_text('\n'.join(generated)+'\n', encoding='utf-8')
    write_json(OUT/'PROFILES.json', dict(packet='3S', runtime_loaded=False, donor_archive=donor,
        unit_source='https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9',
        profiles=manifest_profiles))

    cpp = ['#include "ImpactEnergy.hpp"', '#include <cstdio>', 'using namespace nvo::energy;', 'int main() {']
    evidence = []
    capture_hashes = {}
    for capture_id, (label, rel, expected_hash) in enumerate(CAPTURES, 1):
        path = ROOT / rel
        capture_hashes[rel] = sha(path)
        require(capture_hashes[rel] == expected_hash, 'immutable capture changed')
        parsed = rows(path)
        index = {}
        for kind, row, line in parsed:
            if all(k in row for k in ('session', 'lifetime', 'step')):
                key = tuple(row[k] for k in ('session', 'lifetime', 'step'))
                index.setdefault((kind, key), []).append((row, line))
        for kind, step, line in parsed:
            if kind != 'IMPACT_STEP':
                continue
            key = tuple(step[k] for k in ('session', 'lifetime', 'step'))
            one(index, 'IMPACT_STEP', key)
            companions = {k: one(index, k, key) for k in ('IMPACT_MODEL','IMPACT_VELOCITY','IMPACT_GEOMETRY','IMPACT_BOUNDARY')}
            m, v, g, b = (companions[k][0] for k in ('IMPACT_MODEL','IMPACT_VELOCITY','IMPACT_GEOMETRY','IMPACT_BOUNDARY'))
            require(v['units_calibrated'] == '0' and m['speed_authority'] == m['damage_replacement'] == '0', 'capture authority changed')
            mappings = [r for tag,r,_ in parsed if tag == 'FLIGHT_PROFILE' and r['session'] == step['session']
                        and r['weapon'] == step['weapon'] and r['ammo'] == step['ammo'] and r['projectile_base'] == step['base']]
            require(len(mappings) == 1, 'ambiguous runtime profile mapping')
            mapping = mappings[0]
            # Only these base-game identities are canonicalized. Never mask a
            # random mod's load-order byte or infer a match from an ammo name.
            p = next((p for p in profiles if all(int(p['match'][pk].split(':')[1],16) == int(mapping[rk],16)
                     for pk,rk in [('weapon','weapon'),('ammunition','ammo'),('projectile_base','source_projectile')])), None)
            canonical = [p['match'][k] if p else '' for k in ('weapon','ammunition','projectile_base')]
            row_id = len(evidence)
            evidence.append(dict(index=row_id,capture=label,session=int(key[0]),lifetime=int(key[1]),step=int(key[2]),
                source_line=line, companion_lines={k:val[1] for k,val in companions.items()},
                donor_profile=p['id'] if p else None, original_status=m['status'],
                reported_contact_region=int(step['region']), target=step['target']))
            ident = ','.join([str(capture_id),key[0],key[1],key[2]] + ['0x'+step[k] for k in ('projectile','source','target','weapon','ammo','base')])
            cpp += ['{ Input i{};', 'i.keys={'+','.join(json.dumps(k) for k in canonical)+'};',
                    f'i.contact={{{ident}}}; i.velocity=i.contact;', f'i.profileMappingVerified={int(p is not None)};',
                    f'i.completeSnapshot={int(step["valid_mask"]=="31")}; i.multipleContacts={step["more_contacts"]};',
                    f'i.movementApplied={step["applied"]}; i.baselineVerified={step["baseline_verified"]};',
                    f'i.candidateAvailable={int(m["candidate_valid"]=="1" and m["status"]=="model_estimate_only" and m["geometry_valid"]=="1")};',
                    'i.producer=Producer::'+('OwnedSegmentEstimate' if step['applied']=='1' else 'EngineBaseline')+';',
                    'i.speedUnit=SpeedUnit::MetresPerSimulationSecond; i.clock=Clock::ParentBulletUpdateDelta;']
            values = dict(speed=m['candidate_speed_mps'],dt=step['dt_s'],contactTime=m['candidate_time_s'],
                          unitsPerMetre=v['units_per_metre'],fraction=m['chord_fraction'],tolerance=g['tolerance'],
                          offChord=m['off_chord_units'],modelGap=m['model_contact_gap'],endpointError=b['endpoint_error'],accountingError=b['accounting_error'])
            require(all(math.isfinite(float(x)) for x in values.values()), 'invalid captured numeric input')
            cpp += [f'i.{k}={value};' for k,value in values.items()]
            cpp += ['const auto r=Evaluate(i);',
                    'std::printf("{\\"index\\":%d,\\"reason\\":\\"%s\\",\\"conditional_joules\\":",'+str(row_id)+',ReasonName(r.reason));',
                    'if(r.estimate) std::printf("%.12g",r.estimate->conditionalJoules); else std::printf("null");',
                    'std::puts(",\\"damage_authority\\":false}"); }']
    cpp += ['}']
    (BUILD/'replay.cpp').write_text('\n'.join(cpp)+'\n', encoding='utf-8')
    cmd = f'''@echo off
setlocal
cd /d "%~dp0"
call "C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\Common7\\Tools\\VsDevCmd.bat" -no_logo -arch=x86 -host_arch=x64 >toolchain.log 2>&1
if errorlevel 1 exit /b 1
cl /nologo /MT /O2 /std:c++17 /EHsc /W4 /WX /permissive- /I"{MODEL}" "{MODEL/'ImpactEnergy.cpp'}" "{MODEL/'impact_energy_tests.cpp'}" /Fe:energy_checks.exe /link /INCREMENTAL:NO >checks-build.log 2>&1
if errorlevel 1 exit /b 1
energy_checks.exe >checks.json
if errorlevel 1 exit /b 1
cl /nologo /MT /O2 /std:c++17 /EHsc /W4 /WX /permissive- /I"{MODEL}" "{MODEL/'ImpactEnergy.cpp'}" replay.cpp /Fe:energy_replay.exe /link /INCREMENTAL:NO >replay-build.log 2>&1
if errorlevel 1 exit /b 1
energy_replay.exe >replay.jsonl
exit /b %ERRORLEVEL%
'''
    (BUILD/'RUN.cmd').write_text(cmd, encoding='utf-8')
    subprocess.run(['cmd.exe','/d','/c',str(BUILD/'RUN.cmd')],cwd=BUILD,check=True)
    results=[json.loads(line) for line in (BUILD/'replay.jsonl').read_text().splitlines()]
    require(len(results)==len(evidence), 'incomplete replay output')
    for row, e in zip(results,evidence):
        require(row['index']==e['index'] and not row['damage_authority'], 'output identity/authority mismatch')
        e.update(row)
    counts=Counter(row['reason'] for row in results)
    require(counts['conditional_estimate_only']==4, 'unexpected candidate count; inspect instead of widening acceptance')
    require(all(row['conditional_joules'] is None for row in evidence if row['reported_contact_region']>=0), 'actor evidence changed')
    cmake=(ROOT/'native/NVOCombatCore/CMakeLists.txt').read_text()
    require('ImpactEnergy' not in cmake and 'NVOCombatModel' not in cmake, 'offline module unexpectedly linked')
    install=json.loads((ROOT/'source/combat/step3r1/INSTALL-3R1-result.json').read_text())
    installed={row['path']:sha(GAME/row['path']) for row in install['installed']}
    require(all(installed[row['path']]==row['sha256'] for row in install['installed']), 'normal native323 installation changed')
    sources=[MODEL/name for name in ('ImpactEnergy.hpp','ImpactEnergy.cpp','ImpactEnergyProfiles.inl','impact_energy_tests.cpp')]
    sources += [Path(__file__),pilot_path,donor_meta_path,BUILD/'replay.cpp']
    summary=dict(packet='3S',checks=json.loads((BUILD/'checks.json').read_text()),capture_sha256=capture_hashes,
        contact_records=len(results),outcomes=dict(counts),authoritative_energy_records=0,
        game_loaded=False,game_files_written=False,installed_native_version=323,installed_hashes=installed,
        source_sha256={str(p.relative_to(ROOT)):sha(p) for p in sources},
        limit='Re-evaluates logged diagnostic candidate admission only; does not replay collision physics or prove actual contact speed.')
    write_json(OUT/'REPLAY-RESULT.json',dict(summary=summary,contacts=evidence))
    write_json(OUT/'CHECKS.json',summary)
    print(json.dumps(summary,indent=2))

if __name__=='__main__':
    main()
